### PR TITLE
IMPROVE GERMAN TRANSLATION

### PR DESCRIPTION
**Pull request by MakiWolf**
### Changes
I am quit new here, but I have improved a little bit the German translation

### Testing
- [ ] Tested on a physical device
- [ ] Added or modified unit test cases

### CODE REVIEW

**Comment by ashutoshgngwr** [comment]
Hey @MakiWolf 

While I appreciate the effort, you've only added four missing strings when many of them are missing. Please take a look at #200 and consider adding more translations for me to consider merging this.

**Review by ashutoshgngwr — CHANGES_REQUESTED** [review]
Hey @MakiWolf 

While I appreciate the effort, you've only added four missing strings when many of them are missing. Please take a look at #200 and consider adding more translations for me to consider merging this.

**Comment by MakiWolf** [comment]
I have add more GERMAN TRANSLATION in this commit [https://github.com/ashutoshgngwr/noice/pull/446/commits/ff5546c33f00bbb7624cdfe62e8e3cef1d58310a](https://github.com/ashutoshgngwr/noice/pull/446/commits/ff5546c33f00bbb7624cdfe62e8e3cef1d58310a), but I am quiet new and think that I have made something false when pushing that to Github.

**Comment by ashutoshgngwr** [comment]
@MakiWolf I noticed the issue and fixed it.

PS, if someone else (besides you) pushes a commit to a pull request (or a branch in general), you have to perform `git pull` before pushing again to avoid the issue that you encountered.

**Review by ashutoshgngwr — APPROVED** [review]
Thanks for your contributions. There are still missing translations. If you'd like to add them, consider making another pull request.

PS, sync `master` branch of your fork before making any changes.
```bash
git checkout master
git pull https://github.com/ashutoshgngwr/noice.git master
```

**Pull request merged**
