### PR TITLE
Translate Turkish more precisely

### PR DESCRIPTION
**Pull request by berkaygunduzz**
### Changes
Made these translations more accurate based on real time usage:
- in_app_feedback__description
- mood
- focus
- relax
- intensity
- intensity_description
- dense
- light

### CODE REVIEW

**Comment by ashutoshgngwr** [comment]
Is this ready to review and merge or do you need to make more changes?

**Comment by berkaygunduzz** [comment]
That's it. For now there is no more chages.

**Comment by berkaygunduzz** [comment]
Btw, how can i know that you added new strings in the future?

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz Okay. Regardless, I am going to leave this open until tomorrow in case you decide to add something.

PS, we track translation related changes in #200 for now.

**Comment by berkaygunduzz** [comment]
Ok, thaks.

**Comment by berkaygunduzz** [comment]
Do you want me to do translation more native (more like regular language) rather than official (like goverment official language)? It's more like official now.

**Comment by ashutoshgngwr** [comment]
1. How different is native from official? Are we talking about the same language but different phrases (or PS dialects)?
2. If they are different, which one is more preferred by the people?

**Comment by berkaygunduzz** [comment]
- It's same language. But native uses idioms, figurative meanings etc. while official uses clear, simple language.
- Native is more for projects that want to make their project more candid and friendly for users, official is more for projects that want to make their project more sirious and professional for users.

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz I guess official is fine then.

**Comment by berkaygunduzz** [comment]
Made translation more official and professional.
But why it says it has a conflict now?

**Pull request closed without merging**
