### PR TITLE
Misc gradle things

### PR DESCRIPTION
**Pull request by TacoTheDank**
### Changes
Please describe your changes to provide additional context.
- Delete automatically generated .idea
- Update gradle wrapper
- Group libraries

### Testing
- [x] Tested on a physical device
- [ ] Added or modified unit test cases (none needed)

### Others
- Fixes (none)
- Connects (none)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@ashutoshgngwr Ah, ok. Is just keeping the gradle wrapper update fine?

**Comment by ashutoshgngwr** [comment]
@TacoTheDank Hi!

Thanks for taking the time to submit this PR.

A few things.

- I am not in favour of ignoring Idea related files from Git. It contains some misc config that comes in handy.
- Validating the Gradle wrapper used to be part of Android workflow and got removed in [this commit](https://github.com/ashutoshgngwr/noice/commit/635ace4fcb4ab3bb46e1e9326b1a716fc027818d#diff-ecbecc6c3cdb357e8d5deaa27d76a51c) (apparently by mistake). I think it makes more sense to add the validation step to the Android workflow, and make the Unit test and UI test jobs depend on it.
- I am not sure how grouping libraries adds any significant value. Right now, I keep them organised in chronological order (I find it much better) [so not sure what to do about this]. Why do you want to do this (just curious)?

PS, UI tests are most likely going to fail, ignore those. See #320.

**Comment by TacoTheDank** [comment]
@ashutoshgngwr That's strange. Android is so whack sometimes.

It seems that all the changes here are moot, so I'll close the PR.

I like to group together dependencies because it keeps the related stuff together, and I find that some people have an easier time reading through the dependencies when related libraries are grouped.

As a side note, the codebase of this app is very impressive. I'm in awe at how clean it is. Good job!

**Comment by ashutoshgngwr** [comment]
@TacoTheDank Gradle wrapper validation should be present in one of the workflows. I am in favour of it. If you want, you can add it.

**Pull request closed without merging**
