### PR TITLE
Updated czech translation

### PR DESCRIPTION
**Pull request by Tajnymag**
### Changes
* sorted czech strings.xml to be in the same order as the original one
* added new translations to stay in sync
* changed the czech translation of "Preset" to be "Mix" instead of "Předvolba" as the current translation points more towards a "Settings" meaning then a sound preset
* fixed a typo

### Testing
- [ ] Tested on a physical device
- [ ] Added or modified unit test cases

### CODE REVIEW

**Review by ashutoshgngwr — APPROVED** [review]
Hey @Tajnymag! This looks good.

A gentle reminder that we have moved our translation workflow to [Weblate](https://hosted.weblate.org/projects/noice/). Things are much easier to manage there. We've also switched our default branch to `main`.

I see a few outdated keys. I'll fix them myself. I am about to create a release, so I might as well merge this into it.

**Comment by Tajnymag** [comment]
I know about Webslate. The trouble is, I was not able to translate any key through it's interface. Whenever I filled the form, confirmed/saved the translation, after a refresh, the translation form was clean again without any sign of my impact.

That's why I said myself "screw it" and did the translating manually as I did before.

**Comment by ashutoshgngwr** [comment]
> Whenever I filled the form, confirmed/saved the translation, after a refresh, the translation form was clean again without any sign of my impact.

@Tajnymag That's my bad! I've set the option to add translations as suggestions. So when you were adding new strings, they were being added as suggestions that I can review and merge. Or if they have more than two votes, they get automatically merged. I'll disable that option. I've been told me this exact thing via email once. :sweat_smile:

**Comment by Tajnymag** [comment]
Awesome. Thanks. If it's OK, I'll try it tomorrow morning and will let you know.

**Comment by Tajnymag** [comment]
Seems to be working now. Thank you.

However, I've encountered two issues that I'd like to discuss.

1. Before I was able to properly edit the translations, I had managed to create a new duplicate glossary item with a blank key which I am unable to delete by myself. Or at least haven't found the way.

obrazek

2. Does Weblate update the repo strings in both ways? It seems the manually translated strings from this PR haven't gotten projected to Weblate yet.

**Comment by ashutoshgngwr** [comment]
1. Fixed
2. It syncs repo both ways. The changes should be there. I had to remove a few strings because you were translating on `master` which was about a hundred commits behind `main`.

**Comment by Tajnymag** [comment]
1. Great. Sorry.
2. Ah, ok. I'll translate them again :+1:

**Pull request merged**
