### PR TITLE
Add sound icons

### LINKED ISSUE #596: UI: Images for sounds
### Is your feature request related to a problem? Please describe.

Not at all
### Describe the solution you'd like

It's a UI suggestion, not necessarily needed but would be so great looking. That is, images for sounds like this Windows program does, Ambie, https://github.com/jenius-apps/ambie
image

### PR DESCRIPTION
**Pull request by ashutoshgngwr**
### Changes
- Update sound library UI
- Add two demo icons

### Testing
- [x] Tested on a physical device
- [x] Added or modified unit test cases

### Others
- Resolves #596 

### How to add new icons

- Icons will be placed as end-aligned backgrounds in list items, so consider the following.
   - Icon height can be up to `126dp`. There's no restriction on width, but the icon shouldn't be too wide.
   - Keep your icons monochrome.
   - Background container has horizontal padding set by default but there's no vertical padding. See the howling wolf icon in the preview. Add vertical padding to your icons, horizontal padding is optional.
- Create a vector drawable of the icon using Android Studio.
- Add icon and its credits to the [Sound](https://github.com/ashutoshgngwr/noice/blob/18e7b371b5651eea7bdda6c69a4f004f808f095b/app/src/main/java/com/github/ashutoshgngwr/noice/sound/Sound.kt) class.
- See commit https://github.com/ashutoshgngwr/noice/pull/601/commits/18e7b371b5651eea7bdda6c69a4f004f808f095b for reference.
- Create new PRs against branch [feat/sound-icons](https://github.com/ashutoshgngwr/noice/tree/feat/sound-icons) so we can merge your changes to this pull request.

### Preview

|  |  |
| -- | -- |

### CODE REVIEW

**Comment by Watson15683** [comment]
The Design looks quite promising. I tried to match your style and also made two Images, in Inkscape. One for "River" and one for "Ship".

grafik
grafik

I know these are not Vector Graphics, but GitHub does not accept the "svg" format, so i converted them. If you want the svg, i would be happy to send them to you, if you tell me how.
Unfortunately i am not as technically gifted as to implement the Images myself. 

### Questions
Are the Images generally acceptable? If not how to improve.
Is it ok if i just send you the ".svg" Images?
Do you want me to make more Images? (I could make approximately two per week, since I am quit busy due to school)

**Comment by ashutoshgngwr** [comment]
Hey @Watson15683 Thanks for the quick reply!

> Are the Images generally acceptable?

This is great work really. Much better than anything I could find on [The Noun Project](https://thenounproject.com).

> If not how to improve.

- It'd be easier to import these images if they were tinted black.
- I also think that wider images would look better, but I am not entirely sure. While implementing the UI, I had a 16:9 aspect ratio in consideration.

> Is it ok if i just send you the ".svg" Images?

Yes, that's perfectly fine. I can import them to the Android project myself.

> Do you want me to make more Images? (I could make approximately two per week, since I am quit busy due to school)

If you could speed it up a little, that'd be much better. We have 35 sounds in total and that'd take you 17 weeks at your current speed, which is a little too much. If drawing is too much work and you think you won't be able to do it any faster, just let me know and I can always fall back to [The Noun Project](https://thenounproject.com).

As for attaching files, GitHub luckily supports zip. :)

**Comment by Watson15683** [comment]
### Proposal for the Icons

I made a few more Images. I think it is a good Idea that you choose the ones you like and the ones that work with the Design of the app and substitute the ones you do not like with ones form the TheNounProject or an other source.

### To Do
I did not figure out how the padding thing works, so please add padding manually to the Images.  

### Summary:
**Missing:**
Electric car,  Moving train,  crickets,  Screeching seagulls,  Purring cat,  **Quiet conversation**

**Done by Watson15683:**
Airplane in-flight, Airplane seat-belt beeps,  Creaking ship, Train horn,  Walking through the snow,  Human heartbeat,  Thunder crack,  Distant thunder,  Light rain,  Moderate rain,  Rolling thunder,  Heavy rain,  Morning in a village ,  Night,  Seaside,  Water stream,  Water hose,  Soft wind,  Wind in chimes of shells,  Wind in palm trees,  Office,  Bonfire,  Coffee shop,   Public library,  Brownian noise,  Pink noise,  white_noise

**Done by ashutoshgngwr:**
Howling wolf,  Birds 

Here are the files:
[Github.tar.gz](https://github.com/ashutoshgngwr/noice/files/6367438/Github.tar.gz)

**Comment by ashutoshgngwr** [comment]
Hi @Watson15683 I am importing these icons as I write this.

> I think it is a good Idea that you choose the ones you like

I think overall consistency of icon style outweighs individual icons. I'd prefer all of them to be in the same style.

> I did not figure out how the padding thing works, so please add padding manually to the Images.

That's alright.

> **Missing:**
> Electric car, Moving train, crickets, Screeching seagulls, Purring cat, Quiet conversation

Please draw these as well.

> **Done by ashutoshgngwr:**
> Howling wolf, Birds

I wish. :sweat_smile:

Perhaps you can draw these as well to match the style of other icons..?

> Here are the files:
> Github.tar.gz

Thank you so much!!

**Comment by Watson15683** [comment]
Hey :-)

I will try to do the missing Images in the following week. 

And before i forget, i realised that the letters i put on the "Noise Generators" are not true Vektors but Fonts, and therefore depend on the fonts that are installed on the device. So they might look diffrent from one device to another. 
Maybe the font can somehow be converted to a true Vector.

**Comment by ashutoshgngwr** [comment]
@Watson15683 Yeah, I converted it to a path on my machine. Don't know what font you originally used, but it looks good.

On a side note, perhaps you can edit the shape of the cloud in rain icons? It doesn't look, IMO.

**Comment by Watson15683** [comment]
I will put it on my list. I am actually not happy with the rain cloud as well :-)

**Comment by Watson15683** [comment]
What is IMO? XD

**Comment by ashutoshgngwr** [comment]
> What is IMO? XD

...in my opinion. xD

**Comment by ashutoshgngwr** [comment]
Is this the font you used?

**Comment by ashutoshgngwr** [comment]
The icons in the monsoon section look a little cluttery. All other icons look good. A few icons are missing. Any suggestions?

@Watson15683 I have also optimised birds and howling wolf icons to match the current style so you don't need to draw them again.

|  |  |
|:--:|:--:|
|  |  |
|  |  |
|  |  |

**Comment by Watson15683** [comment]
Hey :-)

First thank you for sharing all the screenshot, it rly helps to get a better idea of what we are talking about and how the images feel in the app.

> The icons in the monsoon section look a little cluttery. 

**Suggestions** that mabye could help unclutter the Monsoon Section:

- make the geometry simple
- make the cloud not a "solid" object, but add holes or sth like that, to reduce the overall gray area.
- maybe make the images smaller or add more padding

> All other icons look good.

I agree, mybe i will revisit the Coffe Mug in the Future, but for now i will focus on the missing items :-)

> I have also optimised birds and howling wolf icons to match the current style so you don't need to draw them again.

Thank you :-)


### to the "Noise Generators"

> Is this the font you used?

Not even close.. xD

I made an updated version. (Things i changed marked in red) If you think the old letters work better in the design, please simly change them back :-)

grafik

Here are the updated files:
[New Noise Genertators.tar.gz](https://github.com/ashutoshgngwr/noice/files/6371893/New.Noise.Genertators.tar.gz)

**Comment by ashutoshgngwr** [comment]
@Watson15683 I had to increase the stroke width of most of these icons. I might have to do it again and it may end up looking the same. I'll replace it as soon as I can.

**Comment by ashutoshgngwr** [comment]
Updated icons

**Comment by Watson15683** [comment]
Hey ashutoshgngwr :-)

I think i am finished now with the Images.

Please read the ReadMe files in the folders for further information.

[Missing and Fixed Images.tar.gz](https://github.com/ashutoshgngwr/noice/files/6410210/Missing.and.Fixed.Images.tar.gz)

**Comment by ashutoshgngwr** [comment]
That's everything. Thanks @Watson15683

**Pull request merged**
